### ISSUE TITLE
Poor performance on `hopper-medium-expert-v2` dataset.

### ISSUE THREAD

**Issue by fuyw** [young-geng/JaxCQL#1]
Many thanks for this implementation. I tried to reproduce the results in the IQL paper (https://arxiv.org/abs/2110.06169) with JaxCQL.

It performs well on the `hopper-medium-v2` dataset, but it performs very poorly on the `hopper-medium-expert-v2` dataset with 1M steps.

**Comment by young-geng** [comment]
I've never tried it on the medium-expert dataset and I will try it out once I have time. Meanwhile you can use my [PyTorch implementation of CQL](https://github.com/young-geng/CQL). The [performance of that implementation](https://wandb.ai/ygx/CQL--cql_min_q_weight_sweep_1?workspace=user-young-geng) has been thoroughly tested.

**Comment by fuyw** [comment]
Thank you so much. It seems that the `cql_random_actions` causes the performance gap:
```
cql_random_actions = jax.random.uniform(split_rng, shape=(batch_size, self.config.cql_n_actions, self.action_dim))
```
only takes random actions in [0, 1], while the pytorch version takes random actions in [-1, 1].

The performance seems much more reasonable with the [-1, 1] random actions.

**Comment by fuyw** [comment]
I will report the performance tomorrow when I have the final result.

**Comment by young-geng** [comment]
Thanks for finding the bug! I'll fix it.

**Comment by fuyw** [comment]
Many thanks. The final performance is close to the results in the IQL paper now.
